### ISSUE TITLE
“[nodemon] clean exit - waiting for changes before restart”

### ISSUE THREAD

**Issue by roferjack** [XHalso/file-preview#3]
这是项目问题还是我本地运行问题，百度的说‘nodemon clean exit’，是啥意思，求教

**Comment by XHalso** [comment]
请问使用的mysql版本是多少，项目里使用的5.7的版本

**Comment by roferjack** [comment]
我是做前端的，没有用mysql，也就是直接下载项目，做配置后，就安装依赖，运行，没有其他操作，请问还需要安装mysql或者其他的吗？

**Comment by XHalso** [comment]
需要安装mysql
